version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    groups:
      production-dependencies:
        dependency-type: "production"
    development-dependencies:
      dependency-type: "development"
