module.exports = {
	extends: ['@antfu', 'turbo', 'prettier'],
	rules: {
		'n/prefer-global/process': 'off',
		'antfu/top-level-function': 'off',
		'sort-imports': 'off',
	},

	// Ignore autogenerated folder
	ignorePatterns: ['packages/database/src/zod/**.ts'],
}
